import pandas as pd
var = pd.read_csv("D:\\Python\\Libraries\\Pandas\\ReadpandasCSV File.csv")
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)
# print(var.replace(to_replace=123,value=22))
# print(var.replace(to_replace="NBIFIN",value="Python"))
# print(var.replace([0,1,2,3,4],12))
# print(var.replace("[A-Za-z]","python", regex =True))
# print(var.replace({"SYMBOL":'[A-Z]'},22, regex=True))
# print(var.replace(123,method="ffill"))
# print(var.replace(123,method="bfill"))
# print(var.replace(123,method="bfill",limit=2))
# print(var.replace(123,method="bfill",limit=2,inplace=True))
# print(var)